name: BotAPI-Generator

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "README*.md"
      - "bin/**"
  push:
    paths-ignore:
      - "README*.md"
      - "bin/**"

jobs:
  runner:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sushrut1101/docker:latest

    steps:
      - uses: actions/checkout@v3
      - name: Run Script
        run: |
          chmod 777 setup.sh
          ./setup.sh

      - name: Commit
        run: |
          git config --global user.name "XelXen"
          git config --global user.email "78258352+XelXen@users.noreply.github.com"
          git config --global credential.helper store
          echo "https://XelXen:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
          cd ~
          git clone https://github.com/LibreTubeAlpha/Telegram-BotAPI-CI bot-ci
          mkdir -p bot-ci/build
          cp telegram-bot-api/bin/* bot-ci/build/
          rm -rfv ~/telegram-bot-api
          cd bot-ci
          git add -f *
          git commit -m "WORKFLOW: BUILD BINARIES"
          git push -u